import { Inter } from 'next/font/google';


import "./globals.css";
import NavBar from "./components/NavBar";
import { GlobalContext } from './contexts/GlobalContext'
import Footer from "./components/Footer";

const inter = Inter({
  weight:['200','700'],
  subsets:['latin'],
  variable: '--font-inter',
});


 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className=''>
        <GlobalContext>
          <NavBar/>
            {children}
          <Footer/>
        </GlobalContext>
      </body>
    </html>
  );
}
