
import "./globals.css";
import NavBar from "./components/NavBar";
import { GlobalContext } from './contexts/GlobalContext'
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalContext>
        <NavBar/>
        {children}
        <Footer/>
        </GlobalContext>
      </body>
    </html>
  );
}
