import { Inter } from 'next/font/google';

import "./globals.css";
import { GlobalContext } from '@/contexts/GlobalContext';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

const inter = Inter({
  weight:['200'],
  subsets:['latin'],
  variable: '--font-inter',
});


 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className='lg:mx-10 xl:mx-50'>
        <GlobalContext>
          <NavBar/>
            {children}
          <Footer/>
        </GlobalContext>
      </body>
    </html>
  );
}


/* 
font-thin
font-extralight
font-light

font-normal
font-medium
font-semibold
font-bold
font-extrabold
font-black

*/